#image: darktips
stages:
  - deploy
before_script:
  # load SSH Key to allow rsync to production server
  - eval $(ssh-agent -s)
  - ssh-add /root/.ssh/id_rsa
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - php -v
demo:
  stage: deploy
  script:
    #- npm install
    # - gulp gitlab
    # Push source files to server
    - rsync -rave ssh  --exclude-from '.rsyncignore' ./ hyder@163.172.90.99:/var/www/toggle.me/public_html
  environment:
    name: WIP
    url: https://toggle.me
  only:
    - master