image: registry.gitlab.com/youhackme/togglex:latest
stages:
  - deploy
before_script:
  # load SSH Key to allow rsync to production server
  - eval $(ssh-agent -s)
  - ssh-add /root/.ssh/id_rsa
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - npm install
  - npm run dev
  - php /composer.phar self-update
  - php /composer.phar -V
  - php /composer.phar install --no-progress
alpha:
  stage: deploy
  script:
    - rsync -rave ssh  --exclude-from '.rsyncignore' ./ hyder@163.172.90.99:/var/www/alpha.toggle.me/public_html
  environment:
    name: Alpha
    url: https://alpha.toggle.me
  only:
    - themescraping
demo:
  stage: deploy
  script:
    - rsync -rave ssh  --exclude-from '.rsyncignore' ./ hyder@163.172.90.99:/var/www/toggle.me/public_html
  environment:
    name: Production
    url: https://toggle.me
  only:
    - master